language: node_js
node_js:
  - '8'
notifications:
  slack:
    secure: h+R2WSCoMDa6XSCPzew9D2IwGx5F98yT+9bRUhapGvdqN/mHjjuIQgrhPCQB6NUBfKhg5HUd+HwougBEReTqzOlh8N0hYSigjANteSdbeV/FH4DFjxNByvnQS2e2tqKPy2T6SSbPv70cgC/GcaNZWQ0I4QyiAxS0Ti9QoJgfe9X8AkE16eSgC88eVidzFtdDgYkyk2Xf2WcNAxngewVFE1gzaIc4A/cToMcerJTffe8GHDu+si2sf1z4bQIcIlHk/HpZl7nfmphcQmAao9q++ph8W3kSXASNBvaBQi1U0P8/4wNeqcmNs1AF14ATixesfd1GXxvuLwsLyWjnS5GrNJ3aKwM75dWw+NoTaHbKbL7nsrJtJrzMvnD5RU7RUd7Hd6HYcjp2fZqrU29V+Gi3IuySGY8xUL1vUAFDKuYNAyf+IHc/6o9v/2cmWEFcwu+jUFg+q/NUT5B2yd2sll5YOsPUg8ORTENoF9vqbaotwVi59Rg2HSeSsa3Ylz3CRmhw5IcwR3fU3eTJgOqo+aOx6URn/heTOFphIRFN7aorjxWQd2SIE+GdSMHWzvOohRYSnsyiTT3LxyenhvUo1leX8NYFyUlvCC/e427XFNYoHAuNtapeleDeVuh7C6DRslsrGjnjsibfcdRgza28CvEk4UjpZjEW9OX+moxCe8ZjM9k=
services:
  - mongodb
  - postgresql
  - redis-server
before_script:
  - psql -c 'create database bustle;' -U postgres